services:
  wsl-docker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:5173"
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "dev"]